# This is a basic workflow to help you get started with Actions

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  name: Quality Check
  quality-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Set Node Version 14
      - name: Use Node V14.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      # Run Linting
      - name: Lint
        run: npm run lint

      # Run Unit Tests
      - name: Unit Test
        run: npm run test
